### PR TITLE
Switch to MPL 2.0

### PR DESCRIPTION
**Pull request by ganwell**
* Change LICENSE file
* Add explicit mpl-boilerplate to amalgamation
* Write about mpl in README.rst

@winged this pull request is meant to seek your agreement about the license change. Also note my the text in README.rst https://github.com/concretecloud/chirp/pull/236/files#diff-88b99bb28683bd5b7e3a204826ead112 Since there are a lot of people out there who don't get that MPL 2.0 is GPL compat I stated this in the README.rst.

do not merge, ignore ci. after rebase it will be ok.

### CODE REVIEW

**Comment by ganwell** [comment]
@winged they both were informed about possible license change to more permissive licenses up to MIT upfront. So they agreed upfront. But lets see what happens.

**Comment by winged** [comment]
It's less about their agreement (which I assumed was given) but about documenting it :)

**Comment by ganwell** [comment]
@keachi thanks a lot!

**Comment by ganwell** [comment]
@winged ah, good point.

**Comment by sosterwalder** [comment]
The switch to MPL 2.0 makes sense, I agree.

**Comment by ganwell** [comment]
Thanks to everyboy

**Pull request merged**
