### PR TITLE
Proceed with documentation: libchirp message header, pool_test and protocol

### PR DESCRIPTION
**Pull request by sosterwalder**

### CODE REVIEW

**Comment by sosterwalder** [comment]
I added two (documentation-) TODOs as I am not sure if my assumptions about the purpose of two members of the protocol struct (ch_protocol_t) are correct:
* .. c:member:: ch_receipt_t* receipts
   Pointer to receipts for this protocol.

* .. c:member:: ch_receipt_t* late_receipts
   Pointer to a set of receipts for this protocol that experience (too) late delivery.

@ganwell: Could you please check those and tell me corrections if necessary?
I will then merge them and remove the TODOs.

**Comment by ganwell** [comment]
@sosterwalder If everything is stable there is one outstanding receipt per connection. If a connection is closed there might be a race and multiple messages might be sent twice. There for the last receipt on a connection is added to late receipts: 

https://github.com/concretecloud/pychirp/blob/master/pychirp/protocol.py#L522

The late receipts are subject to garbage collections.

**Comment by sosterwalder** [comment]
@ganwell Thanks for clearing that up, I improved the documentation based on your input and merged the changes.

**Comment by ganwell** [comment]
@sosterwalder sorry, now it is wrong. :smile_cat: 

There are N connections per protocol, protocol is just a composite of chirp. chirp <-> protocol is 1:1. protocol <-> connection is 1:N. Both in receipts and late_receipts are multiple receipts, but late_receipts must be garbage collected, whereas receipts is maintained by the protocol.

**Comment by ganwell** [comment]
@sosterwalder Something I explained wrong:

If a receipt cannot be managed by the protocol. A late receipt is created as todo: remove receipt X from receipts if it still there after N seconds.

https://github.com/concretecloud/pychirp/blob/master/pychirp/protocol.py#L548

**Comment by ganwell** [comment]
@sosterwalder Wow cool.

**Pull request merged**
